# Generated by Django 4.2.16 on 2024-09-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_onboardingform_windows_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingform',
            name='windows_username',
        ),
        migrations.AddField(
            model_name='onboardingform',
            name='email',
            field=models.EmailField(default='example@alexander-dennis.com', max_length=254),
        ),
    ]
