# Generated by Django 4.2.16 on 2024-09-12 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_department_site_alter_onboardingform_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingform',
            name='manager',
        ),
        migrations.AddField(
            model_name='onboardingform',
            name='manager_email',
            field=models.EmailField(default='manager@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='onboardingform',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='onboarding.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onboardingform',
            name='email',
            field=models.EmailField(default='manager@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='onboardingform',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='onboarding.site'),
            preserve_default=False,
        ),
    ]
