# Generated by Django 4.2.16 on 2024-09-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_remove_onboardingform_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingform',
            name='need_hardware',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='onboardingform',
            name='need_wfh_hardware',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingform',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='onboardingform',
            name='manager_email',
            field=models.EmailField(max_length=254),
        ),
    ]
