# Generated by Django 4.2.16 on 2024-09-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_onboardingform_need_hardware_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
