# Generated by Django 4.2.16 on 2024-09-13 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_hardwareoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingform',
            name='hardware_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onboarding.hardwareoption'),
        ),
        migrations.AlterField(
            model_name='onboardingform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onboardingform',
            name='need_hardware',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='onboardingform',
            name='need_wfh_hardware',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='onboardingform',
            name='site',
            field=models.CharField(max_length=100),
        ),
    ]
