# Generated by Django 4.2.16 on 2024-09-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_onboardingform_hardware_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingform',
            name='reason_for_request',
            field=models.CharField(choices=[('new_starter', 'New Starter'), ('transfer_department', 'Transfer to new department'), ('current_role', 'Item required for current role')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
