# Generated by Django 4.2.16 on 2024-09-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_onboardingform_reason_for_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingform',
            name='reason_for_request',
        ),
    ]
