# Generated by Django 4.2.16 on 2024-09-13 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_remove_onboardingform_reason_for_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingform',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onboarding.site'),
        ),
    ]
