# Generated by Django 5.1.1 on 2024-09-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0012_onboardingform_invoice_automation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingform',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onboarding.department'),
        ),
    ]
